USE historical_apologies;

INSERT INTO Figures(name, style) VALUES
('Napoleon Bonaparte', 'arrogant'),
('Julius Caesar', 'arrogant'),
('George Washington', 'stoic'),
('Cleopatra', 'proper'),
('Winston Churchill', 'stoic'),
('Theodore Roosevelt', 'blunt'),
('Queen Victoria', 'proper'),
('Genghis Khan', 'blunt'),
('Abraham Lincoln', 'stoic'),
('Alexander the Great', 'arrogant'),
('Kim Jong-il', 'arrogant unhinged'),
('Queen Elizabeth I', 'proper'),
('Benito Mussolini', 'arrogant unhinged');

INSERT INTO WordBank (word_type, content) VALUES
/* Figures */
('figure', 'Napoleon Bonaparte'),
('figure', 'Julius Caesar'),
('figure', 'George Washington'),
('figure', 'Cleopatra'),
('figure', 'Winston Churchill'),
('figure', 'Theodore Roosevelt'),
('figure', 'Queen Victoria'),
('figure', 'Genghis Khan'),
('figure', 'Abraham Lincoln'),
('figure', 'Alexander the Great'),
('figure', 'Kim Jong-il'),
('figure', 'Queen Elizabeth I'),
('figure', 'Benito Mussolini'),

/* Recipients */
('recipient', 'the citizens of Rome'),
('recipient', 'my beloved people'),
('recipient', 'the disappointed masses'),
('recipient', 'your esteemed council'),
('recipient', 'the disgruntled goat farmer'),
('recipient', 'the island of Tortuga'),
('recipient', 'the noble patrons of the East Wing Library'),
('recipient', 'the wary diplomats of Prussia'),
('recipient', 'the mill workers of Lower Sheffield'),
('recipient', 'the third regiment of trench diggers'),
('recipient', 'the custodians of the royal hounds'),
('recipient', 'the surviving members of the expedition'),
('recipient', 'the Society for Historical Accuracy'),
('recipient', 'the bakers of the Northern Quarter'),
('recipient', 'the cartographers who warned me'),
('recipient', 'the late-night listeners of Station 12'),
('recipient', 'the bewildered monks of Saint Elwick'),
('recipient', 'the farmers of the disputed valley'),
('recipient', 'the mayor and rats of New Bellington'),
('recipient', 'the scribes who transcribed my panic'),

/* Actions */
('action', 'invading your territory'),
('action', 'burning down the embassy'),
('action', 'mistaking you as a threat'),
('action', '"repurposing" your horses'),
('action', 'tampering with your irrigation systems'),
('action', 'declaring martial law on a whim'),
('action', 'unleashing the experimental cavalary'),
('action', 'reorganizing your leadership structure'),
('action', 'confiscating all available light sources'),
('action', 'stationing troops inside the cathedral'),
('action', 'relocating your archives for "safekeeping"'),
('action', 'testing new protocols on your livestock'),
('action', 'renaming your capital city'),
('action', 'annexing the western provinces'),
('action', 'overstepping several boundaries simultaneously'),
('action', 'summoning the militia without context'),
('action', 'enforcing curfews retroactively'),
('action', 'installing a provisional government'),
('action', 'taking liberties with your charter'),
('action', 'circulating controversial maps'),
('action', 'redistributing your royal heirlooms'),

/* Places */
('place', 'the eastern provinces'),
('place', 'your ancestral homeland'),
('place', 'the state of Kansas'),
('place', 'the outer marshlands'),
('place', 'your winter capital'),
('place', 'the disputed floodplains'),
('place', 'the southern checkpoint'),
('place', 'your family''s ancestral crypt'),
('place', 'the unmarked border village'),
('place', 'the former quarantine zone'),
('place', 'the subterranean council chambers'),
('place', 'your highland outpost'),
('place', 'the neutral trading island'),
('place', 'your favored pilgrimage route'),
('place', 'the last functioning aqueduct'),
('place', 'the camp of the surviving loyalists'),
('place', 'the embankments along the dry river'),
('place', 'the salt flats beyond the treaty line'),
('place', 'the caves rumored to be cursed'),
('place', 'the town square at dusk'),
('place', 'the refugee processing center'),
('place', 'your former administrative zone'),

/* Consequences */
('consequence', 'sank the economy'),
('consequence', 'caused national weeping'),
('consequence', 'ruined Tuesday forever'),
('consequence', 'started a new war'),
('consequence', 'obliterated 24% of the population'),
('consequence', 'collapsed several alliances'),
('consequence', 'triggered mass migration'),
('consequence', 'delayed the harvest by three weeks'),
('consequence', 'increased regional instability'),
('consequence', 'sparked an investigation by neutral powers'),
('consequence', 'bankrupted the local treasury'),
('consequence', 'dismantled centuries of tradition'),
('consequence', 'upset the religious balance'),
('consequence', 'caused twelve resignations'),
('consequence', 'compromised the census'),
('consequence', 'shifted the border file miles east'),
('consequence', 'undermined peace talks'),
('consequence', 'destabilized the clergy'),
('consequence', 'forced a recalibration of the calendar'),
('consequence', 'provoked retaliatory architecture'),
('consequence', 'nullified three ancient treaties'),
('consequence', 'fractured the ruling coalition'),
('consequence', 'disrupted the migration of key species'),
('consequence', 'rewrote regional folklore'),
('consequence', 'unleashed dormant feuds'),
('consequence', 'cast doubt on the legitimacy of the crown'),
('consequence', 'set a dangerous precedent'),

/* Justifications */
('justification', 'the stars aligned'),
('justification', 'it was foretold in my dreams'),
('justification', 'my advisors misread the prophecy'),
('justification', 'I thought it would be funny'),
('justification', 'the omens were unclear'),
('justification', 'my astrologer insisted'),
('justification', 'I was assured it was symbolic'),
('justification', 'we misinterpreted the silence as consent'),
('justification', 'a clerical error escalated'),
('justification', 'I overestimated our popularity'),
('justification', 'it was diplomatically necessary at the time'),
('justification', 'the map was outdated'),
('justification', 'no one objected with sufficient volume'),
('justification', 'the advisory council took a vote'),
('justification', 'tradition demanded swift action'),
('justification', 'we misunderstood the local customs'),
('justification', 'I believed it was a metaphor'),
('justification', 'my double was acting in my stead'),
('justification', 'a mistranslation caused confusion'),
('justification', 'there was pressure to appear decisive'),
('justification', 'we followed the usual procedure'),
('justification', 'the situation was fluid at the time'),
('justification', 'I trusted the wrong oracle'),
('justification', 'the risk assessment was overly optimistic'),
('justification', 'it resolved an older, unrelated dispute'),
('justification', 'we expected a different reaction'),

/* Talents */
('talent', 'do up to seven stomach crunches'),
('talent', 'predict disasters shortly after they happen'),
('talent', 'become gray at will'),
('talent', 'domesticate some animals'),
('talent', 'recite the entire treaty from memory'),
('talent', 'hold my breath for a meaningful amount of time'),
('talent', 'perform a pull-up with full range of motion'),
('talent', 'name several types of cloud with confidence'),
('talent', 'remember the names of at least half the diplomats'),
('talent', 'speak eloquently under light duress'),
('talent', 'draw very lifelike horses'),
('talent', 'accurately gauge the mood of a room, eventually'),
('talent', 'detect mild poisons after ingestion'),
('talent', 'remain almost entirely motionless for approximately 8 hours'),
('talent', 'identify most birds by emotional aura'),
('talent', 'convincingly dismount a horse'),
('talent', 'have a realistic panic attack'),
('talent', 'recall past mistakes with cinematic clarity'),
('talent', 'feign interesting during complex briefings'),
('talent', 'summon enthusiasm on command'),
('talent', 'handwrite in three distinct levels of legibility'),
('talent', 'decipher riddles I personally commissioned'),
('talent', 'walk quietly in ornate footwear'),
('talent', 'recall the exact moment it all went wrong'),
('talent', 'remember faces long after forgetting names'),
('talent', 'convince myself it was necessary'),
('talent', 'stand still while others beg me to act'),
('talent', 'perform duties even when I no longer believe in them'),
('talent', 'translate sorrow into policy'),
('talent', 'go unseen in rooms I once commanded'),
('talent', 'sleep soundly, just not at night'),

/* Facts */
('fact', 'my uncanny ability to fold napkins symmetrically'),
('fact', 'my highly consistent penmanship under cannon fire'),
('fact', 'the way I can spot a pigeon from 400 meters away'),
('fact', 'the fact that I once donated to charity'),
('fact', 'that one time I threw a molotov cocktail through the window of a 7/11'),
('fact', 'my ability to recite every border change since 1634'),
('fact', 'how I kept every letter you ever sent me'),
('fact', 'my brief but passionate interest in cartography'),
('fact', 'the silence I maintained during the inquisition'),
('fact', 'my collection of stones that no one else finds beautiful but are still special to me'),
('fact', 'how I learned to fake a limp to seem more relatable'),
('fact', 'my refusal to blink when questioned'),
('fact', 'the fact that I used to hum lullabies before we launched the fleet'),
('fact', 'my daily walks through the ruins, long after the war'),
('fact', 'how I wept when the statue was unveiled - not from pride, but relief'),
('fact', 'the oath I took alone, before they made me take the public one'),
('fact', 'how I stopped speaking for a week after the census report'),
('fact', 'my decision to stop wearing medals after the incident'),
('fact', 'the small victory garden I kept where the royal court couldn''t see'),
('fact', 'my refusal to appoint a jester, insisting the truth was funny enough'),
('fact', 'the song I sang to myself before the trial'),
('fact', 'the fact that I periodically counted every step from the palace to the gallows');

INSERT INTO Feats(figure_id, content) VALUES
(1, 'leading the French army to dominate Europe during the early 19th century'),
(1, 'crowning myself Emperor in front of the Pope, then placing the crown on my own head'),
(1, 'establishing the Napoleonic Code, a legal framework still influencing many countries today'),
(2, 'conquering Gaul and bringing it into the Roman fold'),
(2, 'being named dictator for life (briefly) before being stabbed a lot'),
(2, 'writing Commentaries on the Gallic War in the third person, for dramatic flair or perhaps for political propaganda'),
(3, 'leading the Continental Army to victory against the British'),
(3, 'voluntarily stepping down from power twice'),
(3, 'refusing to be made king, even when it was basically offered'),
(4, 'mastering multiple languages and ruling Egypt with sharp political skill'),
(4, 'arranging a meeting with Caesar by being smuggled inside a carpet'),
(4, 'aligning Egypt''s interests with both Caesar and Mark Antony'),
(5, 'leading Britain through the darkest days of World War II'),
(5, 'delivering speeches that rallied a nation and echoed throughout history'),
(5, 'winning a Nobel Prize in Literature for historical and biographical writing'),
(6, 'expanding the national parks system to preserve American wilderness'),
(6, 'leading the Rough Riders up San Juan Hill during the Spanish-American War'),
(6, 'negotiating peace in the Russo-Japanese war'),
(7, 'reigning over the British Empire during its peak of global influence'),
(7, 'surviving multiple assassination attempts with unnerving calm'),
(7, 'becoming the symbolic figurehead of an entire era: the Victorian Age'),
(8, 'uniting the Mongol tribes into one of the largest empires in history'),
(8, 'creating a courier system that spanned Eurasia'),
(8, 'enforcing a legal code that protected religious freedom across my empire'),
(9, 'preserving the Union during the American Civil War'),
(9, 'issuing the Emancipation Proclamation to free enslaved people'),
(9, 'delivering the Gettysburg Address in under three minutes'),
(10, 'conquering territory from Greece to India before the age of 33'),
(10, 'founding more than twenty cities that bore my name'),
(10, 'never losing a single battle in over a decade of campaigns'),
(11, 'directing state propaganda to build a cult of personality'),
(11, 'ruling North Korea with absolute control over military and media'),
(11, 'being credited with miraculous accomplishments... according to official sources'),
(12, 'defeating the Spanish Armada and securing England''s naval dominance'),
(12, 'navigating religious conflict to establish Protestant England'),
(12, 'patronizing and encouraging the arts, including the works of Shakespeare'),
(13, 'founding Italian Fascism and becoming "Il Duce"'),
(13, 'modernizing Italy''s infrastructure and transport'),
(13, 'aligning Italy with Nazi Germany');
