INSERT INTO WordBank (word_type, content) VALUES
/* Figures */
('figure', 'Napoleon Bonaparte'),
('figure', 'Julius Caesar'),
('figure', 'George Washington'),
('figure', 'Cleopatra'),
('figure', 'Winston Churchill'),
('figure', 'Theodore Roosevelt'),
('figure', 'Queen Victoria'),
('figure', 'Genghis Khan'),
('figure', 'Abraham Lincoln'),
('figure', 'Alexander the Great'),
('figure', 'Kim Jong-il'),
('figure', 'Queen Elizabeth I'),
('figure', 'Benito Mussolini'),

/* Recipients */
('recipient', 'the citizens of Rome'),
('recipient', 'my beloved people'),
('recipient', 'the disappointed masses'),
('recipient', 'your esteemed council'),
('recipient', 'a disgruntled goat farmer'),
('recipient', 'the island of Tortuga'),

/* Actions */
('action', 'invaded your territory'),
('action', 'burned down the embassy'),
('action', 'mistook you for a threat'),
('action', '"repurposed" your horses'),

/* Places */
('place', 'the eastern provinces'),
('place', 'the royal garden'),
('place', 'your ancestral homeland'),
('place', 'the state of Kansas'),
('place', 'that one cave absolutely crammed FULL of bats'),

/* Consequences */
('consequence', 'sank the economy'),
('consequence', 'caused national weeping'),
('consequence', 'ruined Tuesday forever'),
('consequence', 'started a new war'),
('consequence', 'obliterated 14% of the population'),

/* Justifications */
('justification', 'the stars aligned'),
('justification', 'it was foretold in my dreams'),
('justification', 'my advisors misread the prophecy'),
('justification', 'I thought it would be funny'),

/* Talents */
('talent', 'do seven stomach crunches'),
('talent', 'sneeze louder than everyone else'),
('talent', 'predict disasters shortly after they happen'),
('talent', 'become gray'),
('talent', 'domesticate some animals'),
('talent', 'use a human hand almost as efficiently as a shovel'),

/* Facts */
('fact', 'my uncanny ability to fold napkins symmetrically'),
('fact', 'my highly consistent penmanship under cannon fire'),
('fact', 'the way I can spot a pigeon from 400 meters'),
('fact', 'the fact that I once donated to charity'),
('fact', 'that one time I threw a molotov cocktail at a 7/11'),

INSERT INTO Feats(figure_id, content) VALUES
(0, 'leading the French army to dominate Europe during the early 19th century'),
(0, 'crowning myself Emperor in front of the Pope, then placing the crown on my own head'),
(0, 'established the Napoleonic Code, a legal framework still influencing many countries today'),
(1, 'conquering Gaul and bringing it into the Roman fold'),
(1, 'being named dictator for life (briefly) before being stabbed a lot'),
(1, 'writing Commentaries on the Gallic War in the third person, for dramatic flair or perhaps for political propoganda')
(2, 'leading the Continental Army to victory against the British'),
(2, 'voluntarily stepping down from power, twice'),
(2, 'refusing to be made king, even when it was basically offered'),
(3, 'mastering multiple languages and ruling Egypt with sharp political skill'),
(3, 'arranging a meeting with Caesar by being smuggled inside a carpet'),
(3, 'aligning Egypt''s interests with both Caesar and Mark Antony'),
(4, 'leading Britain through the darkest days of World War II'),
(4, 'delivering speeches that rallied a nation and echoed throughout history'),
(4, 'winning a Nobel Prize in Literature for historical and biographical writing'),
(5, 'expanding the national parks system to preserve American wilderness'),
(5, 'leading the Rough Riders up San Juan Hill during the Spanish-American War'),
(5, 'negotiating peace in the Russo-Japanese war'),
(6, 'reigning over the British Empire during its peak of global influence'),
(6, 'surviving multiple assassination attempts with unnerving calm'),
(6, 'becoming the symbolic figurehead of an entire era: the Victorian Age'),
(7, 'uniting the Mongol tribes into one of the largest empires in history'),
(7, 'creating a courier system that spanned Eurasia'),
(7, 'enforcing a legal code that protected religious freedom across my empire'),
(8, 'preserving the Union during the American Civil War'),
(8, 'issuing the Emancipation Proclamation to free enslaved people'),
(8, 'delivering the Gettysburg Address in under three minutes'),
(9, 'conquering territory from Greece to India before the age of 33'),
(9, 'founding more than twenty cities that bore my name'),
(9, 'never losing a single battle in over a decade of campaigns'),
(10, 'directing state propaganda to build a cult of personality'),
(10, 'ruling North Korea with absolute control over military and media'),
(10, 'being credited with miraculous accomplishments... according to official sources'),
(11, 'defeating the Spanish Armada and securing England''s naval dominance'),
(11, 'navigating religious conflict to establish Protestant England'),
(11, 'patronizing and encouraging the arts, including the works of Shakespeare'),
(12, 'founding Italian Fascism and becoming "Il Duce"'),
(12, 'modernizing Italy''s infrastructure and transport'),
(12, 'aligning Italy with Nazi Germany');
